/**
 * Options « Diplômes délivrés » — même liste que la gestion établissement (`AdminEstablishmentForm`).
 */
export const ESTABLISHMENT_DIPLOMES_DELIVRES_OPTIONS = [
  'CPGE',
  'BTS',
  'DUT',
  'DEUG',
  'DEUST',
  'Technicien spécialisé',
  'Licence',
  'Licence Professionnel',
  "Licence d'excellence",
  'LST',
  'DINAU',
  'Bachelor',
  'Master',
  'Master spécialisé',
  "Cycle d'ingénieur",
  'Cycle de grandes écoles',
  'Médecine',
  "Diplôme d'Architecture",
  'Doctorat',
  // Grades militaires
  'Soldat de deuxième classe',
  'Soldat de première classe',
  'Caporal',
  'Caporal-chef',
  'Sergent',
  'Sergent-chef',
  'Adjudant',
  'Adjudant-chef',
  'Sous-lieutenant',
  'Lieutenant',
  'Capitaine',
  'Commandant',
  'Lieutenant-colonel',
  'Colonel',
  'Colonel-major',
  'Général de brigade',
  'Général de division',
  "Général de corps d'armée",
  "Général d'armée",
  'Gendarme',
  'Officiers',
] as const;
