import type { DiagnosticUiLocale } from '@/constants/schoolDiagnosticLocale';

const FR = {
  youAre: 'Vous êtes',
  student: 'Élève',
  tutor: 'Tuteur',
  firstName: 'Prénom',
  lastName: 'Nom',
  phone: 'Téléphone',
  city: 'Votre ville',
  citiesStudy: 'Villes d’études',
  gender: 'Genre',
  studyLevel: 'Niveau d’études',
  bacType: 'Type de baccalauréat',
  lyceeType: 'Lycée public ou privé',
  bacStream: 'Filière du bac',
  missionSpecs: 'Spécialités bac mission',
  spec1: '1re spécialité',
  spec2: '2e spécialité',
  spec3: '3e spécialité (optionnel)',
  gradesHint: 'Notes facultatives sur 20 (virgule ou point). Une moyenne approximative convient.',
  troncCommun: 'Tronc commun',
  schoolTypes: 'Types d’écoles visées',
  public: 'Public',
  private: 'Privé',
  semiPublic: 'Semi-public',
  military: 'Militaire',
  militarySchools: 'Écoles militaires',
  veilQuestion: 'Portez-vous le voile ?',
  heightQuestion: 'Taille ≥ 1,65 m (F) / 1,70 m (H) ?',
  whereStudy: 'Où souhaitez-vous étudier ?',
  anyCity: 'N’importe quelle ville du Maroc',
  targetCities: 'Villes ciblées',
  citiesStudyField: 'Villes d’études',
  privateIfReject: 'École privée si refus ailleurs ?',
  contests: 'Envisagez-vous de préparer les concours ?',
  contestPrep: 'Préparation aux concours',
  howPrep: 'Comment comptez-vous vous préparer ?',
  prepAlone: 'Seul(e), en autonomie',
  prepCenter: 'Avec un centre de préparation',
  prepOnline: 'Cours en ligne',
  prepMixed: 'Mixte',
  targetLevels: 'Niveaux d’études visés',
  masterSection: 'Master / ingénieur (5 ans)',
  languages: 'Langues d’enseignement acceptées',
  sectorsAttract: 'Secteurs qui vous attirent',
  sectorsLoading: 'Chargement des secteurs…',
  publicThenPrivate: 'Parcours en école publique puis privée',
  split2: '2 ans en public, puis la suite en privé',
  split3: '3 ans en public, puis la suite en privé',
  splitBoth: '2 ou 3 ans au public selon la filière',
  splitNo: 'Non, ce parcours ne me convient pas',
  splitDepends: 'Ça dépend des écoles / coûts',
  freeComment: 'Commentaire libre',
  freeCommentPh: 'Projet, contraintes, écoles déjà identifiées…',
  consent: 'J’accepte l’enregistrement de mes réponses',
  search: 'Rechercher…',
  searchCity: 'Rechercher une ville…',
  emptyPick: 'Aucun résultat',
  loadingCities: 'Chargement des villes…',
  citiesCount: (n: number) => `${n} ville(s)`,
  wizardTitle: 'Diagnostic d’orientation',
  wizardSub: 'Recommandations d’écoles sur mesure',
  back: 'Retour',
  continue: 'Continuer',
  seeRecommendations: 'Voir mes recommandations',
  saving: 'Enregistrement…',
  yes: 'Oui',
  no: 'Non',
  maybe: 'Peut-être',
  unsureSimple: 'Je ne sais pas',
  dependsSimple: 'Ça dépend',
  yesDefinitiveGrade: 'Oui — note définitive',
  noPrevisionnelRange: 'Non — fourchette prévisionnelle',
  noteRangeTitle: 'Fourchette prévisionnelle',
  noteRangeMin: 'Min',
  noteRangeMax: 'Max',
  noteRangeOptional: 'Fourchette estimée — facultatif',
  missionSeconde: 'Seconde',
  gradeSecJihawia: '1re année bac — régional',
  gradeQJihawia: 'Avez-vous reçu votre note régionale définitive ?',
  gradeLblJihawia: 'Note régionale',
  gradeSecSem1Bac: '1er semestre — 2e année bac',
  gradeQSem1Bac: 'Avez-vous reçu votre note du 1er semestre (définitive) ?',
  gradeLblSem1Bac: 'Note du 1er semestre',
  gradeSecBacNat: 'Baccalauréat national',
  gradeQBacNat: 'Avez-vous passé et reçu votre note du baccalauréat national ?',
  gradeLblBacNat: 'Note du baccalauréat national',
  gradeSecPremiereMission: 'Première — bac mission',
  gradeQPremiereMission: 'Avez-vous reçu votre note de Première (définitive) ?',
  gradeLblPremiereMission: 'Note de Première',
  gradeSecS1Mission: 'S1 Terminale — bac mission',
  gradeQS1Mission: 'Avez-vous reçu votre note du 1er semestre de Terminale (définitive) ?',
  gradeLblS1Mission: 'Note S1 Terminale',
  gradeSecBacMission: 'Baccalauréat mission',
  gradeQBacMission: 'Avez-vous passé et reçu votre note du baccalauréat ?',
  gradeLblBacMission: 'Note du baccalauréat',
} as const;

const AR: typeof FR = {
  youAre: 'أنت',
  student: 'تلميذ(ة)',
  tutor: 'ولي / مرافق',
  firstName: 'الاسم الشخصي',
  lastName: 'اسم العائلة',
  phone: 'الهاتف',
  city: 'مدينتك',
  citiesStudy: 'مدن الدراسة',
  gender: 'الجنس',
  studyLevel: 'المستوى الدراسي',
  bacType: 'نوع الباكالوريا',
  lyceeType: 'ثانوية عمومية أو خاصة',
  bacStream: 'شعبة الباك',
  missionSpecs: 'تخصصات الباك الفرنسي',
  spec1: 'التخصص الأول',
  spec2: 'التخصص الثاني',
  spec3: 'التخصص الثالث (اختياري)',
  gradesHint: 'نقط اختيارية على 20. تقدير تقريبي كافٍ.',
  troncCommun: 'الجذع المشترك',
  schoolTypes: 'أنواع المؤسسات المستهدفة',
  public: 'عمومي',
  private: 'خاص',
  semiPublic: 'شبه عمومي',
  military: 'عسكري',
  militarySchools: 'مدارس عسكرية',
  veilQuestion: 'هل ترتدين الحجاب؟',
  heightQuestion: 'القامة ≥ 1,65 م (أنثى) / 1,70 م (ذكر)؟',
  whereStudy: 'أين تريد الدراسة؟',
  anyCity: 'أي مدينة في المغرب',
  targetCities: 'مدن محددة',
  citiesStudyField: 'مدن الدراسة',
  privateIfReject: 'مدرسة خاصة إذا رُفضت في مكان آخر؟',
  contests: 'هل تفكر في التحضير للمباريات؟',
  contestPrep: 'التحضير للمباريات',
  howPrep: 'كيف تنوي التحضير؟',
  prepAlone: 'بمفردي',
  prepCenter: 'مع مركز تحضير',
  prepOnline: 'دروس عن بعد',
  prepMixed: 'مختلط',
  targetLevels: 'المستويات الدراسية المستهدفة',
  masterSection: 'ماستر / مهندس (5 سنوات)',
  languages: 'لغات التدريس المقبولة',
  sectorsAttract: 'قطاعات تجذبك',
  sectorsLoading: 'جاري تحميل القطاعات…',
  publicThenPrivate: 'مسار عمومي ثم خاص',
  split2: 'سنتان عمومي ثم تكملة خاص',
  split3: '3 سنوات عمومي ثم تكملة خاص',
  splitBoth: 'سنتان أو 3 حسب الشعبة',
  splitNo: 'لا، هذا المسار لا يناسبني',
  splitDepends: 'يعتمد على المدارس / التكلفة',
  freeComment: 'تعليق حر',
  freeCommentPh: 'مشروعك، قيود، مدارس محددة…',
  consent: 'أوافق على حفظ إجاباتي',
  search: 'بحث…',
  searchCity: 'بحث عن مدينة…',
  emptyPick: 'لا نتائج',
  loadingCities: 'جاري تحميل المدن…',
  citiesCount: (n: number) => `${n} مدينة`,
  wizardTitle: 'تشخيص التوجيه',
  wizardSub: 'توصيات مدارس مخصصة',
  back: 'رجوع',
  continue: 'متابعة',
  seeRecommendations: 'عرض توصياتي',
  saving: 'جاري الحفظ…',
  yes: 'نعم',
  no: 'لا',
  maybe: 'ربما',
  unsureSimple: 'لا أعرف',
  dependsSimple: 'يعتمد',
  yesDefinitiveGrade: 'نعم — نقطة نهائية',
  noPrevisionnelRange: 'لا — تقدير تقريبي (من – إلى)',
  noteRangeTitle: 'نطاق تقديري',
  noteRangeMin: 'من',
  noteRangeMax: 'إلى',
  noteRangeOptional: 'نطاق تقديري — اختياري',
  missionSeconde: 'السنة الثانية',
  gradeSecJihawia: 'الأولى باك — جهوي',
  gradeQJihawia: 'هل استلمت نقطتك الجهوية النهائية؟',
  gradeLblJihawia: 'النقطة الجهوية',
  gradeSecSem1Bac: 'الدورة الأولى — الثانية باك',
  gradeQSem1Bac: 'هل استلمت نقطة الدورة الأولى (نهائية)؟',
  gradeLblSem1Bac: 'نقطة الدورة الأولى',
  gradeSecBacNat: 'الباك الوطني',
  gradeQBacNat: 'هل اجتزت واستلمت نقطة الباك الوطني؟',
  gradeLblBacNat: 'نقطة الباك الوطني',
  gradeSecPremiereMission: 'الأولى — باك فرنسي',
  gradeQPremiereMission: 'هل استلمت نقطة الأولى (نهائية)؟',
  gradeLblPremiereMission: 'نقطة الأولى',
  gradeSecS1Mission: 'الدورة الأولى — النهائية (باك فرنسي)',
  gradeQS1Mission: 'هل استلمت نقطة الدورة الأولى للنهائية (نهائية)؟',
  gradeLblS1Mission: 'نقطة الدورة الأولى (النهائية)',
  gradeSecBacMission: 'باك فرنسي',
  gradeQBacMission: 'هل اجتزت واستلمت نقطة الباك؟',
  gradeLblBacMission: 'نقطة الباك',
};

export function getDiagnosticFormLabels(locale: DiagnosticUiLocale) {
  return locale === 'ar' ? AR : FR;
}

export const INGENIEUR_MASTER_PATH_QUESTION_I18N = {
  fr: {
    title: 'Comment envisagez-vous d’accéder au diplôme ingénieur ou master ?',
    hint: 'Au Maroc, le titre ingénieur (5 ans) passe le plus souvent par une licence (Bac+2), une prépa CPGE ou des concours d’entrée (ENSA, INPT, grandes écoles…). Choisissez la voie qui vous ressemble le plus.',
  },
  ar: {
    title: 'كيف تتصور الوصول إلى دبلوم مهندس أو ماستر؟',
    hint: 'في المغرب، مسار المهندس (5 سنوات) يمر غالباً بالإجازة (باك+2)، التحضيرية أو مباريات القبول. اختر المسار الأقرب لك.',
  },
} as const;
